# Generated by Django 4.2.1 on 2023-07-24 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_company_alter_employee_employee_id_employee_company'),
    ]

    operations = [
        migrations.AlterField(
           model_name='employee',
        name='company',
           field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.Company', null=True),
),
    ]
