# Generated by Django 4.2.1 on 2023-07-27 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
