# Generated by Django 4.1.3 on 2023-09-17 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_alter_employee_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='name',
            new_name='full_name',
        ),
    ]
